// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyIntroShop2._2.Main;

namespace MyIntroShop2._2.Migrations
{
    [DbContext(typeof(DBContent))]
    [Migration("20200204145754_add ssds")]
    partial class addssds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MotherboardCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardCategoryId");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.MotherboardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("MotherboardCategories");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PhoneCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("PhoneCategoryId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.PhoneCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("PhoneCategories");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Procesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProcesorCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("ProcesorCategoryId");

                    b.ToTable("Procesors");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.ProcesorCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("ProcesorCategories");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RamCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("RamCategoryId");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.RamCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("RamCategories");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Ssd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SsdCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("SsdCategoryId");

                    b.ToTable("Ssds");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.SsdCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("SsdCategories");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Motherboard", b =>
                {
                    b.HasOne("MyIntroShop2._2.Main.Models.MotherboardCategory", "MotherboardCategory")
                        .WithMany("motherboards")
                        .HasForeignKey("MotherboardCategoryId");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Phone", b =>
                {
                    b.HasOne("MyIntroShop2._2.Main.Models.PhoneCategory", "PhoneCategory")
                        .WithMany("phones")
                        .HasForeignKey("PhoneCategoryId");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Procesor", b =>
                {
                    b.HasOne("MyIntroShop2._2.Main.Models.ProcesorCategory", "ProcesorCategory")
                        .WithMany("procesors")
                        .HasForeignKey("ProcesorCategoryId");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Ram", b =>
                {
                    b.HasOne("MyIntroShop2._2.Main.Models.RamCategory", "RamCategory")
                        .WithMany("rams")
                        .HasForeignKey("RamCategoryId");
                });

            modelBuilder.Entity("MyIntroShop2._2.Main.Models.Ssd", b =>
                {
                    b.HasOne("MyIntroShop2._2.Main.Models.SsdCategory", "SsdCategory")
                        .WithMany("ssds")
                        .HasForeignKey("SsdCategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
